package com.nsd.noa.cxf.service.util

import org.junit.Test

class _NoaServiceUtilsKtTest {

    @Test
    fun `should test`() {
        println("<ACORD>\n" +
                "    <InsuranceSvcRq>\n" +
                "        <CommlPkgPolicyQuoteInqRq>\n" +
                "            <RqUID>7b3db4f0-6261-4a89-86f1-3ea0857fec9d</RqUID>\n" +
                "            <TransactionRequestDt>2018-06-07T12:28:44-05:00</TransactionRequestDt>\n" +
                "            <TransactionEffectiveDt>2018-06-07T12:28:44-05:00</TransactionEffectiveDt>\n" +
                "            <CurCd>USD</CurCd>\n" +
                "            <BroadLOBCd>C</BroadLOBCd>\n" +
                "            <ACORDStandardVersionCd>1300</ACORDStandardVersionCd>\n" +
                "            <Producer>\n" +
                "                <GeneralPartyInfo>\n" +
                "                    <NameInfo>\n" +
                "                        <CommlName>\n" +
                "                            <CommercialName>Risk Services Central, Inc.</CommercialName>\n" +
                "                        </CommlName>\n" +
                "                    </NameInfo>\n" +
                "                    <Addr>\n" +
                "                        <Addr1>Chicago IL Office</Addr1>\n" +
                "                        <Addr2>200 East Randolph</Addr2>\n" +
                "                        <City>Chicago</City>\n" +
                "                        <StateProvCd>IL</StateProvCd>\n" +
                "                        <PostalCode>60601</PostalCode>\n" +
                "                    </Addr>\n" +
                "                    <Communications>\n" +
                "                        <PhoneInfo>\n" +
                "                            <PhoneTypeCd>Phone</PhoneTypeCd>\n" +
                "                            <PhoneNumber>3123811000</PhoneNumber>\n" +
                "                        </PhoneInfo>\n" +
                "                        <EmailInfo>\n" +
                "                            <EmailAddr>Alfred.Anderon@noa.com</EmailAddr>\n" +
                "                        </EmailInfo>\n" +
                "                    </Communications>\n" +
                "                </GeneralPartyInfo>\n" +
                "                <ProducerInfo>\n" +
                "                    <ProducerRoleCd>Agency</ProducerRoleCd>\n" +
                "                </ProducerInfo>\n" +
                "            </Producer>\n" +
                "            <InsuredOrPrincipal>\n" +
                "                <ItemIdInfo>\n" +
                "                    <AgencyId>10224406</AgencyId>\n" +
                "                </ItemIdInfo>\n" +
                "                <GeneralPartyInfo>\n" +
                "                    <NameInfo>\n" +
                "                        <CommlName>\n" +
                "                            <CommercialName>Morgan Services Inc</CommercialName>\n" +
                "                        </CommlName>\n" +
                "                        <TaxIdentity>\n" +
                "                            <TaxIdTypeCd>FEIN</TaxIdTypeCd>\n" +
                "                            <TaxId>12-3456789</TaxId>\n" +
                "                        </TaxIdentity>\n" +
                "                    </NameInfo>\n" +
                "                    <Addr>\n" +
                "                        <Addr1>323 North Michigan Avenue</Addr1>\n" +
                "                        <City>Chicago</City>\n" +
                "                        <StateProvCd>IL</StateProvCd>\n" +
                "                        <PostalCode>60601</PostalCode>\n" +
                "                    </Addr>\n" +
                "                </GeneralPartyInfo>\n" +
                "                <InsuredOrPrincipalInfo>\n" +
                "                    <InsuredOrPrincipalRoleCd>Insured</InsuredOrPrincipalRoleCd>\n" +
                "                    <BusinessInfo>\n" +
                "                        <SICCd>3679</SICCd>\n" +
                "                        <FinancialStatementInfo>\n" +
                "                            <TotalRevenueAmt>\n" +
                "                                <Amt>49101000</Amt>\n" +
                "                            </TotalRevenueAmt>\n" +
                "                        </FinancialStatementInfo>\n" +
                "                    </BusinessInfo>\n" +
                "                </InsuredOrPrincipalInfo>\n" +
                "            </InsuredOrPrincipal>\n" +
                "            <CommlPolicy>\n" +
                "                <ContractTerm>\n" +
                "                    <EffectiveDt>2018-09-01</EffectiveDt>\n" +
                "                    <ExpirationDt>2019-09-01</ExpirationDt>\n" +
                "                </ContractTerm>\n" +
                "                <NumLosses>True</NumLosses>\n" +
                "                <OtherOrPriorPolicy>\n" +
                "                    <PolicyTypeCd>Underly</PolicyTypeCd>\n" +
                "                    <LOBCd>CGL</LOBCd>\n" +
                "                    <LOBSubCd>NPO</LOBSubCd>\n" +
                "                    <Coverage>\n" +
                "                        <CoverageCd>FIRDM</CoverageCd>\n" +
                "                        <Limit>\n" +
                "                            <FormatInteger>500000</FormatInteger>\n" +
                "                        </Limit>\n" +
                "                    </Coverage>\n" +
                "                    <Coverage>\n" +
                "                        <CoverageCd>PIADV</CoverageCd>\n" +
                "                        <Limit>\n" +
                "                            <FormatInteger>1000000</FormatInteger>\n" +
                "                        </Limit>\n" +
                "                    </Coverage>\n" +
                "                    <Coverage>\n" +
                "                        <CoverageCd>EAOCC</CoverageCd>\n" +
                "                        <Limit>\n" +
                "                            <FormatInteger>1000000</FormatInteger>\n" +
                "                        </Limit>\n" +
                "                    </Coverage>\n" +
                "                    <Coverage>\n" +
                "                        <CoverageCd>MEDEX</CoverageCd>\n" +
                "                        <Limit>\n" +
                "                            <FormatInteger>10000</FormatInteger>\n" +
                "                        </Limit>\n" +
                "                    </Coverage>\n" +
                "                    <Coverage>\n" +
                "                        <CoverageCd>GENAG</CoverageCd>\n" +
                "                        <Limit>\n" +
                "                            <FormatInteger>10000000</FormatInteger>\n" +
                "                        </Limit>\n" +
                "                    </Coverage>\n" +
                "                    <Coverage>\n" +
                "                        <CoverageCd>PRDCO</CoverageCd>\n" +
                "                        <Limit>\n" +
                "                            <FormatInteger>2000000</FormatInteger>\n" +
                "                        </Limit>\n" +
                "                    </Coverage>\n" +
                "                </OtherOrPriorPolicy>\n" +
                "                <PaymentOption>\n" +
                "                    <PaymentPlanCd>QT</PaymentPlanCd>\n" +
                "                </PaymentOption>\n" +
                "                <PolicyStatusCd>RWL</PolicyStatusCd>\n" +
                "            </CommlPolicy>\n" +
                "            <CommlPolicy>\n" +
                "                <NumLosses>0</NumLosses>\n" +
                "            </CommlPolicy>\n" +
                "            <Location>\n" +
                "                <Addr>\n" +
                "                    <Addr1>2200 Milan Road</Addr1>\n" +
                "                    <City>Toledo</City>\n" +
                "                    <StateProvCd>OH</StateProvCd>\n" +
                "                    <PostalCode>44113</PostalCode>\n" +
                "                </Addr>\n" +
                "                <SubLocation>\n" +
                "                    <Addr>\n" +
                "                        <Addr2>Sta C, Box 1642</Addr2>\n" +
                "                    </Addr>\n" +
                "                </SubLocation>\n" +
                "            </Location>\n" +
                "            <GeneralLiabilityLineBusiness>\n" +
                "                <LOBSubCd>NPO</LOBSubCd>\n" +
                "                <LiabilityInfo>\n" +
                "                    <CommlCoverage>\n" +
                "                        <CoverageCd>PIADV</CoverageCd>\n" +
                "                        <Limit>\n" +
                "                            <FormatInteger>1000000</FormatInteger>\n" +
                "                        </Limit>\n" +
                "                    </CommlCoverage>\n" +
                "                    <CommlCoverage>\n" +
                "                        <CoverageCd>PRDCO</CoverageCd>\n" +
                "                        <Limit>\n" +
                "                            <FormatInteger>2000000</FormatInteger>\n" +
                "                        </Limit>\n" +
                "                    </CommlCoverage>\n" +
                "                    <CommlCoverage>\n" +
                "                        <CoverageCd>MEDEX</CoverageCd>\n" +
                "                        <Limit>\n" +
                "                            <FormatInteger>10000</FormatInteger>\n" +
                "                        </Limit>\n" +
                "                    </CommlCoverage>\n" +
                "                    <CommlCoverage>\n" +
                "                        <CoverageCd>EAOCC</CoverageCd>\n" +
                "                        <Limit>\n" +
                "                            <FormatInteger>1000000</FormatInteger>\n" +
                "                        </Limit>\n" +
                "                    </CommlCoverage>\n" +
                "                    <CommlCoverage>\n" +
                "                        <CoverageCd>GENAG</CoverageCd>\n" +
                "                        <Limit>\n" +
                "                            <FormatInteger>10000000</FormatInteger>\n" +
                "                            <LimitAppliesToCd>PerPolicy</LimitAppliesToCd>\n" +
                "                        </Limit>\n" +
                "                    </CommlCoverage>\n" +
                "                    <CommlCoverage>\n" +
                "                        <CoverageCd>EBLIAl</CoverageCd>\n" +
                "                        <Option>\n" +
                "                            <OptionTypeCd>Num1</OptionTypeCd>\n" +
                "                            <OptionValue>1</OptionValue>\n" +
                "                        </Option>\n" +
                "                    </CommlCoverage>\n" +
                "                    <CommlCoverage>\n" +
                "                        <CoverageCd>EBLIA</CoverageCd>\n" +
                "                        <Limit>\n" +
                "                            <FormatInteger>1000000</FormatInteger>\n" +
                "                        </Limit>\n" +
                "                    </CommlCoverage>\n" +
                "                    <CommlCoverage>\n" +
                "                        <CoverageCd>FIRDM</CoverageCd>\n" +
                "                        <Limit>\n" +
                "                            <FormatInteger>500000</FormatInteger>\n" +
                "                        </Limit>\n" +
                "                    </CommlCoverage>\n" +
                "                    <GeneralLiabilityClassification>\n" +
                "                        <ClassCd>70050</ClassCd>\n" +
                "                        <ClassCdDesc>All operations Composite Rated</ClassCdDesc>\n" +
                "                    </GeneralLiabilityClassification>\n" +
                "                </LiabilityInfo>\n" +
                "            </GeneralLiabilityLineBusiness>\n" +
                "            <CommlUmbrellaLineBusiness>\n" +
                "                <LOBSubCd>OCCUR</LOBSubCd>\n" +
                "                <CommlCoverage>\n" +
                "                    <CoverageCd>CUMBR</CoverageCd>\n" +
                "                    <Limit>\n" +
                "                        <FormatInteger>20000000</FormatInteger>\n" +
                "                        <LimitAppliesToCd>Aggregate</LimitAppliesToCd>\n" +
                "                    </Limit>\n" +
                "                    <Limit>\n" +
                "                        <FormatInteger>25000000</FormatInteger>\n" +
                "                        <LimitAppliesToCd>PerOcc</LimitAppliesToCd>\n" +
                "                    </Limit>\n" +
                "                    <Deductible>\n" +
                "                        <FormatInteger>25000</FormatInteger>\n" +
                "                    </Deductible>\n" +
                "                </CommlCoverage>\n" +
                "                <FirstDollarDefenseInd>Y</FirstDollarDefenseInd>\n" +
                "                <QuestionAnswer>\n" +
                "                    <QuestionCd>CUMBR24</QuestionCd>\n" +
                "                    <YesNoCd>True</YesNoCd>\n" +
                "                </QuestionAnswer>\n" +
                "            </CommlUmbrellaLineBusiness>\n" +
                "            <CommlPropertyLineBusiness />\n" +
                "        </CommlPkgPolicyQuoteInqRq>\n" +
                "    </InsuranceSvcRq>\n" +
                "</ACORD>\n".toEmailBody())
    }
}
