package com.nsd.noa.service;

import com.nsd.noa.schema.ObjectFactory;
import com.nsd.noa.schema.PostResponse;
import com.nsd.noa.schema.PostRq;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-09-18T19:28:07.997-05:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://www.nsd.com/noa/schema", name = "NoaLinkService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface NoaLinkService {

    @WebMethod(action = "http://www.nsd.com/noa/service/postRequest")
    @WebResult(name = "postResponse", targetNamespace = "http://www.nsd.com/noa/schema", partName = "postResponse")
    public PostResponse postRequest(
            @WebParam(partName = "postRq", name = "PostRq", targetNamespace = "http://www.nsd.com/noa/schema")
                    PostRq postRq
    );
}
