
package com.nsd.noa.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import com.nsd.noa.schema.PostResponse;
import com.nsd.noa.schema.PostRq;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-09-18T19:28:07.948-05:00
 * Generated source version: 3.2.5
 *
 */
public final class NoaLinkService_NoaLinkServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.nsd.com/noa/schema", "NoaLinkServiceImplService");

    private NoaLinkService_NoaLinkServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = NoaLinkServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        NoaLinkServiceImplService ss = new NoaLinkServiceImplService(wsdlURL, SERVICE_NAME);
        NoaLinkService port = ss.getNoaLinkServiceImplPort();

        {
        System.out.println("Invoking postRequest...");
        PostRq _postRequest_postRq = null;
        PostResponse _postRequest__return = port.postRequest(_postRequest_postRq);
        System.out.println("postRequest.result=" + _postRequest__return);


        }

        System.exit(0);
    }

}
